Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,7 +22,11 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        if exist requirements.txt (pip install -r requirements.txt) else (echo "No requirements.txt found")
+        if (Test-Path requirements.txt) {
+            pip install -r requirements.txt
+        } else {
+            echo "No requirements.txt found"
+        }
         pip install pyinstaller
 
     - name: Build executable with PyInstaller
@@ -38,6 +42,15 @@ jobs:
     - name: Install Inno Setup
       run: |
         choco install innosetup --version=6.2.0 -y
+
+    - name: Verify Inno Setup Installation
+      run: |
+        if (Test-Path "C:\Program Files (x86)\Inno Setup 6\ISCC.exe") {
+            echo "Inno Setup is installed correctly."
+        } else {
+            echo "ISCC.exe not found at the specified path."
+            exit 1
+        }
 
     - name: Create Inno Setup Script
       run: |
